# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u6570\u636e\u5e93ID')),
                ('Name', models.CharField(max_length=255, unique=True, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ChangeTime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('Note', models.TextField(max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('SystemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.System', verbose_name='\u7cfb\u7edfId')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('view_databases', '\u53ef\u4ee5\u67e5\u770b\u6570\u636e\u5e93'), ('add_databases', '\u53ef\u4ee5\u6dfb\u52a0\u6570\u636e\u5e93'), ('change_databases', '\u53ef\u4ee5\u7f16\u8f91\u6570\u636e\u5e93'), ('delete_databases', '\u53ef\u4ee5\u5220\u9664\u6570\u636e\u5e93')),
            },
        ),
    ]
