# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0002_remove_host_systemid'),
        ('Databases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='HostId',
            field=models.ManyToManyField(to='Host.Host', verbose_name='\u4e3b\u673aId'),
        ),
    ]
