# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7cfb\u7edfID')),
                ('Name', models.CharField(max_length=255, unique=True, verbose_name='\u7cfb\u7edf\u540d\u79f0')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ChangeTime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('Note', models.TextField(max_length=255, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('view_system', '\u53ef\u4ee5\u67e5\u770b\u7cfb\u7edf\u5217\u8868'), ('add_system', '\u53ef\u4ee5\u6dfb\u52a0\u7cfb\u7edf'), ('change_system', '\u53ef\u4ee5\u7f16\u8f91\u7cfb\u7edf'), ('delete_system', '\u53ef\u4ee5\u5220\u9664\u7cfb\u7edf')),
            },
        ),
    ]
