# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='permission_id',
            field=models.CharField(error_messages={'field-permission_id': '\u8f93\u5165\u6743\u9650'}, help_text='\u7ed9\u83dc\u5355\u8bbe\u7f6e\u4e00\u4e2a\u7f16\u53f7\uff0c\u7528\u4e8e\u6743\u9650\u63a7\u5236', max_length=250, verbose_name='\u6743\u9650\u7f16\u53f7'),
        ),
    ]
