# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='DC',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='\u6570\u636e\u4e2d\u5fc3'),
            preserve_default=False,
        ),
    ]
