# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u4e3b\u673aID')),
                ('Name', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('Ip', models.CharField(max_length=255, verbose_name='\u4e3b\u673aIP')),
                ('Status', models.CharField(max_length=255, verbose_name='\u72b6\u6001')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ChangeTime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('Note', models.TextField(max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('SystemId', models.ManyToManyField(to='System.System', verbose_name='\u7cfb\u7edfId')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('view_host', '\u53ef\u4ee5\u67e5\u770b\u4e3b\u673a'), ('add_host', '\u53ef\u4ee5\u6dfb\u52a0\u4e3b\u673a'), ('change_host', '\u53ef\u4ee5\u7f16\u8f91\u4e3b\u673a'), ('delete_host', '\u53ef\u4ee5\u5220\u9664\u4e3b\u673a')),
            },
        ),
    ]
