# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('view_reports', '\u67e5\u770b\u62a5\u544a'),),
            },
        ),
    ]
