# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McObject',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u76d1\u63a7\u5bf9\u8c61Id')),
                ('Name', models.CharField(max_length=255, verbose_name='\u76d1\u63a7\u5bf9\u8c61\u540d\u79f0')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ChangeTime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='McObjectClass',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u76d1\u63a7\u7c7bId')),
                ('Name', models.CharField(max_length=255, unique=True, verbose_name='\u76d1\u63a7\u7c7b\u540d\u79f0')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ChangeTime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='McParameter',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u76d1\u63a7\u53c2\u6570Id')),
                ('Name', models.CharField(max_length=255, unique=True, verbose_name='\u76d1\u63a7\u53c2\u6570\u540d\u79f0')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ChangeTime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'default_permissions': [],
            },
        ),
    ]
