# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u76d1\u63a7\u8be6\u60c5Id')),
                ('object_id', models.PositiveIntegerField()),
                ('ItemValue', models.CharField(max_length=250, verbose_name='\u503c')),
                ('ItemValueUnit', models.CharField(max_length=250, verbose_name='\u5355\u4f4d')),
                ('OccurrenceTime', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u751f\u65f6\u95f4')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('McObjectClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.McObjectClass', verbose_name='\u5bf9\u8c61\u7c7b')),
                ('McObjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.McObject', verbose_name='\u5bf9\u8c61\u7c7b')),
                ('McParameterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.McParameter', verbose_name='\u53c2\u6570')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'default_permissions': [],
            },
        ),
    ]
